//
//  Octicons.swift
//  OctoViewer
//
//  Created by Hesham Salman on 5/26/17.
//  Copyright © 2017 Hesham Salman
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

import Foundation

struct Octicons {
  static let alert = "\u{f02d}"
  static let alignmentAlign = "\u{f08a}"
  static let alignmentAlignedTo = "\u{f08e}"
  static let alignmentUnalign = "\u{f08b}"
  static let arrowDown = "\u{f03f}"
  static let arrowLeft = "\u{f040}"
  static let arrowRight = "\u{f03e}"
  static let arrowSmallDown = "\u{f0a0}"
  static let arrowSmallLeft = "\u{f0a1}"
  static let arrowSmallRight = "\u{f071}"
  static let arrowSmallUp = "\u{f09f}"
  static let arrowUp = "\u{f03d}"
  static let beer = "\u{f069}"
  static let book = "\u{f007}"
  static let bookmark = "\u{f07b}"
  static let briefcase = "\u{f0d3}"
  static let broadcast = "\u{f048}"
  static let browser = "\u{f0c5}"
  static let bug = "\u{f091}"
  static let calendar = "\u{f068}"
  static let check = "\u{f03a}"
  static let checklist = "\u{f076}"
  static let chevronDown = "\u{f0a3}"
  static let chevronLeft = "\u{f0a4}"
  static let chevronRight = "\u{f078}"
  static let chevronUp = "\u{f0a2}"
  static let circleSlash = "\u{f084}"
  static let circuitBoard = "\u{f0d6}"
  static let clippy = "\u{f035}"
  static let clock = "\u{f046}"
  static let cloudDownload = "\u{f00b}"
  static let cloudUpload = "\u{f00c}"
  static let code = "\u{f046}"
  static let colorMode = "\u{f065}"
  static let comment = "\u{f02b}"
  static let commentDiscussion = "\u{f04f}"
  static let creditCard = "\u{f045}"
  static let dash = "\u{f0ca}"
  static let dashboard = "\u{f07d}"
  static let database = "\u{f096}"
  static let deviceCamera = "\u{f056}"
  static let deviceCameraVideo = "\u{f057}"
  static let deviceDesktop = "\u{f27c}"
  static let deviceMobile = "\u{f038}"
  static let diff = "\u{f04d}"
  static let diffAdded = "\u{f06b}"
  static let diffIgnored = "\u{f099}"
  static let diffModified = "\u{f06d}"
  static let diffRemoved = "\u{f06c}"
  static let diffRenamed = "\u{f06e}"
  static let ellipsis = "\u{f09a}"
  static let eye = "\u{f04e}"
  static let fileBinary = "\u{f094}"
  static let fileCode = "\u{f010}"
  static let fileDirectory = "\u{f016}"
  static let fileMedia = "\u{f012}"
  static let filePdf = "\u{f014}"
  static let fileSubmodule = "\u{f017}"
  static let fileSymlinkDirectory = "\u{f0b1}"
  static let fileSymlinkFile = "\u{f0b0}"
  static let fileText = "\u{f011}"
  static let fileZip = "\u{f013}"
  static let flame = "\u{f0d2}"
  static let fold = "\u{f0cc}"
  static let gear = "\u{f02f}"
  static let gift = "\u{f042}"
  static let gist = "\u{f00e}"
  static let gistSecret = "\u{f08c}"
  static let gitBranch = "\u{f020}"
  static let gitCommit = "\u{f01f}"
  static let gitCompare = "\u{f0ac}"
  static let gitMerge = "\u{f023}"
  static let gitPullRequest = "\u{f009}"
  static let globe = "\u{f0b6}"
  static let graph = "\u{f043}"
  static let heart = "\u{2665}"
  static let history = "u{f07e}"
  static let home = "\u{f08d}"
  static let horizontalRule = "\u{f070}"
  static let hourglass = "\u{f09e}"
  static let hubot = "\u{f09d}"
  static let inbox = "\u{f0cf}"
  static let info = "\u{f059}"
  static let issueClosed = "\u{f028}"
  static let issueOpened = "\u{f026}"
  static let issueReopened = "\u{f027}"
  static let jersey = "\u{f019}"
  static let jumpDown = "\u{f072}"
  static let jumpLeft = "\u{f0a5}"
  static let jumpRight = "\u{f0a6}"
  static let jumpUp = "\u{f073}"
  static let key = "\u{f049}"
  static let keyboard = "\u{f00d}"
  static let law = "\u{f0d8}"
  static let lightBulb = "\u{f000}"
  static let link = "\u{f05c}"
  static let linkExternal = "\u{f07f}"
  static let listOrdered = "\u{f062}"
  static let listUnordered = "\u{f061}"
  static let location = "\u{f060}"
  static let lock = "\u{f06a}"
  static let logoGithub = "\u{f092}"
  static let mail = "\u{f03b}"
  static let mailRead = "\u{f03c}"
  static let mailReply = "\u{f051}"
  static let markGithub = "\u{f00a}"
  static let markdown = "\u{f0c9}"
  static let megaphone = "\u{f077}"
  static let mention = "\u{f0be}"
  static let microscope = "\u{f089}"
  static let milestone = "\u{f075}"
  static let mirror = "\u{f024}"
  static let mortarBoard = "\u{f0d7}"
  static let moveDown = "\u{f0a8}"
  static let moveLeft = "\u{f074}"
  static let moveRight = "\u{f0a9}"
  static let moveUp = "\u{f0a7}"
  static let mute = "\u{f080}"
  static let noNewline = "\u{f09c}"
  static let octoface = "\u{f008}"
  static let organization = "\u{f037}"
  static let package = "\u{f0c4}"
  static let paintcain = "\u{f0d1}"
  static let pencil = "\u{f058}"
  static let person = "\u{f018}"
  static let pin = "\u{f041}"
  static let playbackFastForward = "\u{f0bd}"
  static let playbackPause = "\u{f0bb}"
  static let playbackPlay = "\u{f0bf}"
  static let playbackRewind = "\u{f0bc}"
  static let plug = "\u{f0d4}"
  static let plus = "\u{f05d}"
  static let podium = "\u{f0af}"
  static let primitiveDot = "\u{f052}"
  static let primitiveSquare = "\u{f053}"
  static let pulse = "\u{f085}"
  static let puzzle = "\u{f0c0}"
  static let question = "\u{f02c}"
  static let quote = "\u{f063}"
  static let radioTower = "\u{f030}"
  static let repo = "\u{f001}"
  static let repoClone = "\u{f04c}"
  static let repoForcePush = "\u{f04a}"
  static let repoForked = "\u{f002}"
  static let repoPull = "\u{f006}"
  static let repoPush = "\u{f005}"
  static let rocket = "\u{f033}"
  static let rss = "\u{f034}"
  static let ruby = "\u{f047}"
  static let screenFull = "\u{f066}"
  static let screenNormal = "\u{f067}"
  static let search = "\u{f02e}"
  static let server = "\u{f097}"
  static let settings = "\u{f07c}"
  static let signin = "\u{f032}"
  static let signout = "\u{f032}"
  static let split = "\u{f0c6}"
  static let squirrel = "\u{f0b2}"
  static let star = "\u{f02a}"
  static let steps = "\u{f0c7}"
  static let stop = "\u{f08f}"
  static let sync = "\u{f087}"
  static let tag = "\u{f015}"
  static let telescope = "\u{f088}"
  static let terminal = "\u{f0c8}"
  static let threeBars = "\u{f05e}"
  static let thumbsDown = "\u{f0db}"
  static let thumbsUp = "\u{f0da}"
  static let tools = "\u{f031}"
  static let trashcan = "\u{f0d0}"
  static let triangleDown = "\u{f05b}"
  static let triangleLeft = "\u{f044}"
  static let triangleRight = "\u{f05a}"
  static let triangleUp = "\u{f0aa}"
  static let unfold = "\u{f039}"
  static let unmute = "\u{f0ba}"
  static let versions = "\u{f064}"
  static let x = "\u{f081}"
  static let zap = "\u{26A1}"
}
